/**
 * Inbound REST adapter. Controllers implement OpenAPI-generated server-stub
 * interfaces from {@link com.trawhile.adapter.inbound.web.api}; request/response
 * DTOs are generated into {@link com.trawhile.adapter.inbound.web.dto}.
 * Both are generated by the {@code openapi-generator-maven-plugin} from
 * {@code spec/openapi.yaml}; never hand-author types that duplicate generated
 * shapes.
 */
package com.trawhile.adapter.inbound.web;
