-- trawhile — PostgreSQL schema (authoritative)
-- One instance = one company. No multi-tenancy.
-- All timestamps TIMESTAMPTZ in UTC per UR-00-C10.
-- All primary keys UUID generated by gen_random_uuid().
-- System configuration lives in application.yml / environment variables (architecture §8.8); no settings table.
-- Audit events go to the application log stream (architecture §8.5); no audit table.

-- ============================================================================
-- Node tree
-- Root node: parent_id IS NULL (singleton, seeded by Flyway).
-- All entities (projects, work packages, tasks, absence types, etc.) are nodes.
-- A leaf node with `is_active = true` and no active children is trackable.
-- ============================================================================

CREATE TABLE nodes (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id       UUID        REFERENCES nodes(id),
  display_name    TEXT        NOT NULL,
  description     TEXT,
  color           TEXT,                              -- CSS hex e.g. '#4A90D9'
  icon            TEXT,                              -- PrimeIcons identifier e.g. 'pi-briefcase'
  logo            BYTEA,                             -- up to 256 KB decoded; SR-02-F03.F02
  logo_mime_type  TEXT,                              -- one of 'image/png', 'image/jpeg', 'image/svg+xml', 'image/webp'
  is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
  sort_order      INTEGER     NOT NULL DEFAULT 0,
  deactivated_at  TIMESTAMPTZ,                       -- non-NULL ⇔ is_active = false
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (octet_length(coalesce(logo, ''::bytea)) <= 262144),                -- 256 KB cap (SR-02-F03.F02)
  CHECK ((logo IS NULL) = (logo_mime_type IS NULL)),                        -- logo and mime travel together
  CHECK (deactivated_at IS NULL OR is_active = false)
);

CREATE INDEX nodes_parent_id_idx ON nodes (parent_id);

-- ============================================================================
-- Users
-- A user is in one of three states:
--   * pending   : `pending_invitations` row exists, `users.anonymised_at IS NULL`,
--                 0 `user_oauth_providers` rows
--   * active    : `users.anonymised_at IS NULL`, ≥ 1 `user_oauth_providers` row,
--                 no `pending_invitations` row
--   * anonymised: `users.anonymised_at IS NOT NULL`, identifying fields NULL,
--                 0 `user_oauth_providers` rows (cleared by SR-07-F01.F01 step 5)
-- The anonymised stub persists for the lifetime of the deployment (SR-07-F01.C01).
-- ============================================================================

CREATE TABLE users (
  id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  display_name  TEXT,                                -- NOT NULL on active rows; NULL on anonymised
  email         VARCHAR(320),                        -- NOT NULL on active rows; NULL on anonymised; RFC 5321 max length
  anonymised_at TIMESTAMPTZ,                         -- non-NULL ⇔ user is anonymised
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (anonymised_at IS NOT NULL OR display_name IS NOT NULL),
  CHECK (anonymised_at IS NOT NULL OR email IS NOT NULL)
);

-- Non-anonymised users have a unique email (SR-01-F04.F01 invitation collision check).
CREATE UNIQUE INDEX users_active_email_unique
  ON users (email)
  WHERE anonymised_at IS NULL;

-- ============================================================================
-- User OIDC provider links
-- Per UR-00-C11 / SR-05-F03.C01: a non-anonymised user holds ≥ 1 row here.
-- Invariant is enforced by the persistence port: `unlinkProvider` uses an
-- atomic-SQL guard subquery; `scrubProviders` (the cleanup path) bypasses it
-- because by then `users.anonymised_at IS NOT NULL`. No DB trigger.
-- ============================================================================

CREATE TABLE user_oauth_providers (
  id        UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id   UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider  VARCHAR(255) NOT NULL,                   -- registration id from SR-00-C02.F02
  subject   VARCHAR(512) NOT NULL,                   -- OIDC `sub` claim
  linked_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  UNIQUE (provider, subject),
  UNIQUE (user_id, provider)
);

CREATE INDEX user_oauth_providers_user_id_idx ON user_oauth_providers (user_id);

-- ============================================================================
-- User profile (per-user mutable state that survives anonymisation)
-- last_report_filters: JSONB blob per SR-04-F07.F01 / SR-04-F07.C01.
-- ============================================================================

CREATE TABLE user_profile (
  user_id              UUID  PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  last_report_filters  JSONB
);

-- ============================================================================
-- Pending invitations
-- Created with a pre-allocated `users` row (display_name and email set).
-- Consumed at the matching OIDC callback (UR-01-F13) or by the lifecycle
-- expiry job after 90 days (UR-00-C13).
-- ============================================================================

CREATE TABLE pending_invitations (
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID         NOT NULL UNIQUE REFERENCES users(id),
  email       VARCHAR(320) NOT NULL UNIQUE,                       -- RFC 5321 max length
  invited_by  UUID         REFERENCES users(id) ON DELETE SET NULL,
  invited_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  expires_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW() + INTERVAL '90 days'
);

CREATE INDEX pending_invitations_expires_at_idx ON pending_invitations (expires_at);

-- ============================================================================
-- Authorization
-- One direct grant per (user, node) pair. Per UR-02-F07 the level overwrites
-- on second submit (raise, lower, or keep). The recursive grant rule
-- (architecture §8.2) makes a grant on N effective on N and all descendants.
-- ============================================================================

CREATE TYPE auth_level AS ENUM ('view', 'track', 'admin');
-- Definition order matters: view < track < admin.
-- track subsumes view; admin subsumes track.

CREATE TABLE node_authorizations (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  node_id     UUID        NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  user_id     UUID        NOT NULL REFERENCES users(id),
  auth_level  auth_level  NOT NULL,
  granted_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (node_id, user_id)
);

CREATE INDEX node_authorizations_user_id_idx ON node_authorizations (user_id);

-- Helper: nodes visible to a user via the recursive grant rule.
-- Direct grant on N → N and all descendants visible.
CREATE FUNCTION visible_nodes(p_user_id UUID)
RETURNS TABLE (node_id UUID)
LANGUAGE sql STABLE
AS $$
  WITH RECURSIVE visible AS (
    SELECT n.id
    FROM nodes n
    JOIN node_authorizations na ON na.node_id = n.id
    WHERE na.user_id = p_user_id
    UNION ALL
    SELECT n.id
    FROM nodes n
    JOIN visible v ON n.parent_id = v.id
  )
  SELECT DISTINCT id AS node_id FROM visible
$$;

-- Helper: effective authorization level of a user on a specific node.
-- Walks the ancestor chain; returns NULL if no grant is effective.
CREATE FUNCTION effective_auth(p_user_id UUID, p_node_id UUID)
RETURNS auth_level
LANGUAGE sql STABLE
AS $$
  WITH RECURSIVE ancestors AS (
    SELECT id, parent_id FROM nodes WHERE id = p_node_id
    UNION ALL
    SELECT n.id, n.parent_id
    FROM nodes n
    JOIN ancestors a ON n.id = a.parent_id
  )
  SELECT MAX(na.auth_level)
  FROM ancestors a
  JOIN node_authorizations na ON na.node_id = a.id
  WHERE na.user_id = p_user_id
$$;

-- Helper: users with at least the given level on a node (direct or inherited).
CREATE FUNCTION users_with_min_auth(p_node_id UUID, p_min_level auth_level)
RETURNS TABLE (user_id UUID, effective_level auth_level)
LANGUAGE sql STABLE
AS $$
  WITH RECURSIVE ancestors AS (
    SELECT id, parent_id FROM nodes WHERE id = p_node_id
    UNION ALL
    SELECT n.id, n.parent_id
    FROM nodes n
    JOIN ancestors a ON n.id = a.parent_id
  )
  SELECT na.user_id, MAX(na.auth_level) AS effective_level
  FROM ancestors a
  JOIN node_authorizations na ON na.node_id = a.id
  GROUP BY na.user_id
  HAVING MAX(na.auth_level) >= p_min_level
$$;

-- ============================================================================
-- Time records
-- At most one open record per user (partial unique index).
-- No-overlap invariant: enforced at the write path (SR-03-F08.F01 / SR-03-F09.F01 / SR-03-F11.F01).
-- 24-hour duration cap: enforced by the open-record auto-close lifecycle job.
-- ============================================================================

CREATE TABLE time_records (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES users(id),
  node_id      UUID        NOT NULL REFERENCES nodes(id),
  started_at   TIMESTAMPTZ NOT NULL,
  ended_at     TIMESTAMPTZ,
  description  TEXT,                                  -- max 256 Unicode chars (SR-03-F03.C01)
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (ended_at IS NULL OR ended_at >= started_at),
  CHECK (description IS NULL OR char_length(description) <= 256)
);

CREATE UNIQUE INDEX time_records_one_open_per_user
  ON time_records (user_id)
  WHERE ended_at IS NULL;

CREATE INDEX time_records_user_started_idx ON time_records (user_id, started_at);
CREATE INDEX time_records_node_started_idx ON time_records (node_id, started_at);

-- ============================================================================
-- Quick access (per-user pinned nodes)
-- Max 9 entries per user (SR-03-F07.C01); enforced at the write path.
-- ============================================================================

CREATE TABLE quick_access (
  id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  node_id     UUID    NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  UNIQUE (user_id, node_id)
);

CREATE INDEX quick_access_user_idx ON quick_access (user_id);

-- ============================================================================
-- API keys
-- Immutable artifacts after creation: only `revoked_at` and `last_used_at`
-- may be mutated post-insert (SR-08-F03.C02 — enforced by the persistence
-- port shape, which exposes only insert / markRevoked / markLastUsed; no
-- update on name / scope / expires_at / key_hash / user_id / created_at).
-- Scope is a single (node, level) pair; through inheritance the key carries
-- `scope_level` on `scope_node_id` and all descendants.
-- Raw key never stored; only SHA-256 hash retained.
-- ============================================================================

CREATE TABLE api_keys (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name           TEXT        NOT NULL,
  scope_node_id  UUID        NOT NULL REFERENCES nodes(id),
  scope_level    auth_level  NOT NULL,
  key_hash       VARCHAR(64) NOT NULL UNIQUE,         -- SHA-256 hex of the raw key value (exactly 64 hex chars)
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at     TIMESTAMPTZ NOT NULL,
  last_used_at   TIMESTAMPTZ,
  revoked_at     TIMESTAMPTZ,
  CHECK (char_length(name) <= 64),                                          -- SR-08-F01.C01
  CHECK (expires_at > created_at)
  -- The 1-year max lifetime (SR-08-F01.C02) is enforced by the application
  -- service of SR-08-F01.F01 at create time, and the persistence port (SR-08-F03.C02)
  -- exposes no path that mutates expires_at post-creation; no DB CHECK is needed.
);

CREATE INDEX api_keys_user_id_idx ON api_keys (user_id);

-- ============================================================================
-- Webhook subscriptions (per-user)
-- Configuration is owned by the Authorization service (architecture §5.3.3).
-- The raw signing secret is returned exactly once at creation and rotation
-- (SR-03-F12.F03); only its hash is persisted here.
-- ============================================================================

CREATE TABLE webhook_subscriptions (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint_url        TEXT        NOT NULL,
  signing_secret_hash TEXT        NOT NULL,
  status              TEXT        NOT NULL DEFAULT 'active',                -- 'active' | 'paused' | 'revoked'
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  rotated_at          TIMESTAMPTZ
);

CREATE INDEX webhook_subscriptions_user_idx ON webhook_subscriptions (user_id);

-- ============================================================================
-- Webhook delivery outbox
-- Transactional outbox per SR-03-F12.F04: every emitted event writes one row
-- per matching subscription in the same transaction as the originating
-- business mutation. A background worker claims rows with
-- `FOR UPDATE SKIP LOCKED` (SR-03-F12.C01) and POSTs with HMAC signing and
-- retry-and-backoff. At-least-once delivery semantics.
-- ============================================================================

CREATE TABLE webhook_deliveries (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_id UUID        NOT NULL REFERENCES webhook_subscriptions(id) ON DELETE CASCADE,
  event_type      TEXT        NOT NULL,
  payload         JSONB       NOT NULL,
  status          TEXT        NOT NULL DEFAULT 'pending',                   -- 'pending' | 'delivered' | 'transient_failure' | 'permanent_failure'
  attempt_count   INTEGER     NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_status     TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  delivered_at    TIMESTAMPTZ
);

CREATE INDEX webhook_deliveries_pending_idx
  ON webhook_deliveries (next_attempt_at)
  WHERE status = 'pending';

CREATE INDEX webhook_deliveries_subscription_idx
  ON webhook_deliveries (subscription_id);

-- ============================================================================
-- Purge job state
-- Resumable on restart; cutoff_date stable across restarts (idempotency anchor).
-- Seeded by Flyway with one singleton row per job_type.
-- ============================================================================

CREATE TABLE purge_jobs (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_type        VARCHAR(64) NOT NULL UNIQUE,                              -- see comment below for the enum
  status          TEXT        NOT NULL DEFAULT 'idle',                      -- 'idle' | 'active'
  cutoff_date     DATE,
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  deleted_counts  JSONB,
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (job_type IN ('time_record_retention', 'node_retention', 'invitation_expiry', 'open_record_auto_close'))
);
