-- trawhile — V1: full schema
-- Proposed replacement for src/main/resources/db/migration/V1__create_schema.sql
-- Aligned with docs/schema.sql and the current contract docs.

-- All tables use UUID primary keys generated by gen_random_uuid().
-- One instance = one company. No multi-tenancy.
-- Table order respects FK dependencies.
--
-- System configuration (name, timezone, freeze-offset-years, retention-years,
-- node-retention-extra-years, privacy-notice-url) lives in
-- application.yml / environment variables — not in the database.

-- ---------------------------------------------------------------------------
-- Node tree
-- Root node: parent_id IS NULL (singleton, seeded below).
-- All entities (projects, work packages, tasks, absence types, etc.) are nodes.
-- Leaf node (no active children) = trackable.
-- ---------------------------------------------------------------------------

CREATE TABLE nodes (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id      UUID        REFERENCES nodes(id),
  name           TEXT        NOT NULL,
  description    TEXT,
  is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
  sort_order     INTEGER     NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deactivated_at TIMESTAMPTZ,                        -- set on deactivation, cleared on reactivation
  color          TEXT,                               -- CSS hex color e.g. '#4A90D9'; optional
  icon           TEXT,                               -- PrimeIcons identifier e.g. 'pi-briefcase'; optional
  logo           BYTEA,                              -- uploaded image, max 256 KB; takes precedence over icon
  logo_mime_type TEXT                                -- MIME type of logo e.g. 'image/png'
);

-- ---------------------------------------------------------------------------
-- Users
-- users: anchor record; FK target for all historical data.
--   Deleted only when no time_records or requests reference it (invitation expiry, withdrawal, or
--   anonymization with no retained history). Otherwise retained as an anonymous stub indefinitely.
-- user_profile: personal data; deleted on anonymization (cascades to user_oauth_providers,
--   quick_access). mcp_tokens reference users directly, are soft-revoked (revoked_at) on
--   anonymization/removal, and are hard-deleted via ON DELETE CASCADE when the users row
--   is eventually deleted.
-- pending_invitations.invited_by: nullable; SET NULL when the inviter's users row is deleted.
-- No picture_url stored — profile pictures dropped (privacy; no chat/mention feature).
-- System Admin = user with admin authorization on the root node (no separate flag).
-- ---------------------------------------------------------------------------

CREATE TABLE users (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE user_profile (
  id                    UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID    NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  name                  TEXT    NOT NULL,
  last_report_settings  JSONB                            -- last used report filter state; persisted for multi-device consistency
);

CREATE TABLE user_oauth_providers (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES user_profile(id) ON DELETE CASCADE,
  provider   TEXT NOT NULL,  -- 'google' | 'apple' | 'microsoft' | 'keycloak'
  subject    TEXT NOT NULL,  -- provider's subject ID (never email)
  UNIQUE (provider, subject)
);

-- Pending invitations. A users row is created immediately on invite.
-- Deleted (along with the users row) when: the user completes first login (GDPR acknowledgement
-- — user_profile is then created); the invitation is withdrawn by a System Admin; or the
-- invitation expires after 90 days. In all cases no time_records or requests exist yet at that point.
CREATE TABLE pending_invitations (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL UNIQUE REFERENCES users(id),
  email      TEXT        NOT NULL UNIQUE,
  invited_by UUID        REFERENCES users(id) ON DELETE SET NULL,
  invited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '90 days'
);

-- ---------------------------------------------------------------------------
-- Authorization
-- ---------------------------------------------------------------------------

CREATE TYPE auth_level AS ENUM ('view', 'track', 'admin');
-- Ordering: view < track < admin (PostgreSQL ENUM preserves definition order)
-- track implies view; admin implies track.
-- A grant on node N is effective on N and all its descendants (recursive CTE).

CREATE TABLE node_authorizations (
  id            UUID       PRIMARY KEY DEFAULT gen_random_uuid(),
  node_id       UUID       NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  user_id       UUID       NOT NULL REFERENCES users(id),
  authorization auth_level NOT NULL,
  UNIQUE (node_id, user_id)
);

-- ---------------------------------------------------------------------------
-- Time records
-- Active record: ended_at IS NULL. Partial unique index enforces at most one per user.
-- timezone: IANA string captured from browser at tracking start; stored on the record.
-- ---------------------------------------------------------------------------

CREATE TABLE time_records (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES users(id),
  node_id     UUID        NOT NULL REFERENCES nodes(id),
  started_at  TIMESTAMPTZ NOT NULL,
  ended_at    TIMESTAMPTZ,
  timezone    TEXT        NOT NULL,             -- IANA string from browser; private (discloses coarse location) — protected by per-owner access control on time_records
  description TEXT,                             -- optional short note by the member
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX time_records_one_active_per_user
  ON time_records (user_id)
  WHERE ended_at IS NULL;

-- ---------------------------------------------------------------------------
-- Personal preferences (cascade-deleted with user_profile on anonymization)
-- ---------------------------------------------------------------------------

CREATE TABLE quick_access (
  id         UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID    NOT NULL REFERENCES user_profile(id) ON DELETE CASCADE,
  node_id    UUID    NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  UNIQUE (profile_id, node_id)
);

-- ---------------------------------------------------------------------------
-- Requests (in-app request board)
-- ---------------------------------------------------------------------------

CREATE TABLE requests (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id UUID        NOT NULL REFERENCES users(id),
  node_id      UUID        NOT NULL REFERENCES nodes(id),
  template     TEXT        NOT NULL,  -- system template ID or 'free_text'
  body         TEXT,
  status       TEXT        NOT NULL DEFAULT 'open',  -- 'open' | 'closed'
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at  TIMESTAMPTZ,
  resolved_by  UUID        REFERENCES users(id)
);

-- ---------------------------------------------------------------------------
-- Security event log (90-day retention, System Admin access only)
-- ---------------------------------------------------------------------------

CREATE TABLE security_events (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        REFERENCES users(id),  -- NULL for pre-auth events
  event_type  TEXT        NOT NULL,
  details     JSONB,
  ip_address  TEXT,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Purge job state
-- Two singleton rows are seeded below: job_type = 'activity', job_type = 'node'.
-- status: 'idle' | 'active'
-- cutoff_date: set at job start, stable across restarts (idempotency anchor).
-- deleted_counts: running tally updated after each batch commit.
-- On startup: any 'active' row is resumed using stored cutoff_date.
-- ---------------------------------------------------------------------------

CREATE TABLE purge_jobs (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_type        TEXT        NOT NULL UNIQUE,  -- 'activity' | 'node'
  status          TEXT        NOT NULL DEFAULT 'idle',
  cutoff_date     DATE,
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  deleted_counts  JSONB,
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- MCP access tokens (Epic 9)
-- Raw token never stored. Only SHA-256 hash retained.
-- Revocation: soft-delete via revoked_at. Hard-delete not needed (hash is useless after revoke).
-- ---------------------------------------------------------------------------

CREATE TABLE mcp_tokens (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash   TEXT        NOT NULL UNIQUE,  -- SHA-256 hex of the raw token
  label        TEXT        NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  expires_at   TIMESTAMPTZ,                  -- NULL = non-expiring
  revoked_at   TIMESTAMPTZ                   -- NULL = active
);

CREATE INDEX mcp_tokens_user_id_idx ON mcp_tokens (user_id);

-- ---------------------------------------------------------------------------
-- Seeds
-- ---------------------------------------------------------------------------

-- Root node (parent_id IS NULL identifies the unique root)
INSERT INTO nodes (id, name, is_active, sort_order)
VALUES ('00000000-0000-0000-0000-000000000001', 'root', TRUE, 0);

-- Purge job state singletons
INSERT INTO purge_jobs (job_type, status) VALUES ('activity', 'idle');
INSERT INTO purge_jobs (job_type, status) VALUES ('node', 'idle');
