-- trawhile — V1: full schema
-- All tables use UUID primary keys generated by gen_random_uuid().
-- One instance = one company. No multi-tenancy.
-- Table order respects FK dependencies.

-- ---------------------------------------------------------------------------
-- Company settings (singleton, one row seeded by Flyway)
-- ---------------------------------------------------------------------------

CREATE TABLE company_settings (
  id                         UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  name                       TEXT    NOT NULL,
  timezone                   TEXT    NOT NULL DEFAULT 'UTC',
  freeze_date                DATE,
  retention_years            INTEGER NOT NULL DEFAULT 7,
  node_retention_extra_years INTEGER NOT NULL DEFAULT 1,
  purge_schedule             TEXT    NOT NULL DEFAULT 'annual',
  privacy_notice_url         TEXT
);

-- ---------------------------------------------------------------------------
-- Node tree
-- Root node: parent_id IS NULL (singleton, seeded by Flyway).
-- Leaf node (no active children) = trackable.
-- ---------------------------------------------------------------------------

CREATE TABLE nodes (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id      UUID        REFERENCES nodes(id),
  name           TEXT        NOT NULL,
  description    TEXT,
  is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
  sort_order     INTEGER     NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deactivated_at TIMESTAMPTZ,
  color          TEXT,
  icon           TEXT,
  logo           BYTEA,
  logo_mime_type TEXT
);

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------

CREATE TABLE users (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
  is_system_admin BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE user_profile (
  id                    UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID    NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  name                  TEXT    NOT NULL,
  gdpr_notice_accepted  BOOLEAN NOT NULL DEFAULT FALSE,
  language              TEXT    NOT NULL DEFAULT 'en',
  last_report_settings  JSONB
);

CREATE TABLE user_oauth_providers (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES user_profile(id) ON DELETE CASCADE,
  provider   TEXT NOT NULL,
  subject    TEXT NOT NULL,
  UNIQUE (provider, subject)
);

-- Email-only invitations. Matched on first OAuth2 login then deleted.
-- Automatically purged after 90 days if not accepted (GDPR storage limitation).
CREATE TABLE pending_memberships (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  email      TEXT        NOT NULL UNIQUE,
  invited_by UUID        NOT NULL REFERENCES users(id),
  invited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '90 days'
);

-- ---------------------------------------------------------------------------
-- Authorization
-- ---------------------------------------------------------------------------

CREATE TYPE auth_level AS ENUM ('view', 'track', 'admin');

CREATE TABLE node_authorizations (
  id            UUID       PRIMARY KEY DEFAULT gen_random_uuid(),
  node_id       UUID       NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  user_id       UUID       NOT NULL REFERENCES users(id),
  authorization auth_level NOT NULL,
  UNIQUE (node_id, user_id)
);

-- ---------------------------------------------------------------------------
-- Time entries
-- Active entry: ended_at IS NULL. Partial unique index enforces at most one per user.
-- ---------------------------------------------------------------------------

CREATE TABLE time_entries (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES users(id),
  node_id     UUID        NOT NULL REFERENCES nodes(id),
  started_at  TIMESTAMPTZ NOT NULL,
  ended_at    TIMESTAMPTZ,
  timezone    TEXT        NOT NULL,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX time_entries_one_active_per_user
  ON time_entries (user_id)
  WHERE ended_at IS NULL;

-- ---------------------------------------------------------------------------
-- Personal preferences (cascade-deleted with user_profile on anonymization)
-- ---------------------------------------------------------------------------

CREATE TABLE quick_access (
  id         UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID    NOT NULL REFERENCES user_profile(id) ON DELETE CASCADE,
  node_id    UUID    NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  UNIQUE (profile_id, node_id)
);

-- ---------------------------------------------------------------------------
-- Requests (in-app request board)
-- ---------------------------------------------------------------------------

CREATE TABLE requests (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id UUID        NOT NULL REFERENCES users(id),
  node_id      UUID        NOT NULL REFERENCES nodes(id),
  template     TEXT        NOT NULL,
  body         TEXT,
  status       TEXT        NOT NULL DEFAULT 'open',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at  TIMESTAMPTZ,
  resolved_by  UUID        REFERENCES users(id)
);

-- ---------------------------------------------------------------------------
-- Security event log (90-day retention, System Admin access only)
-- ---------------------------------------------------------------------------

CREATE TABLE security_events (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        REFERENCES users(id),
  event_type  TEXT        NOT NULL,
  details     JSONB,
  ip_address  TEXT,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Purge job state (two singleton rows seeded by Flyway)
-- ---------------------------------------------------------------------------

CREATE TABLE purge_jobs (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_type        TEXT        NOT NULL UNIQUE,
  status          TEXT        NOT NULL DEFAULT 'idle',
  cutoff_date     DATE,
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  deleted_counts  JSONB,
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- MCP access tokens (Epic 9)
-- Raw token never stored. Only SHA-256 hash retained.
-- ---------------------------------------------------------------------------

CREATE TABLE mcp_tokens (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES users(id),
  token_hash   TEXT        NOT NULL UNIQUE,
  label        TEXT        NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  expires_at   TIMESTAMPTZ,
  revoked_at   TIMESTAMPTZ
);

CREATE INDEX mcp_tokens_user_id_idx ON mcp_tokens (user_id);

-- ---------------------------------------------------------------------------
-- Seeds
-- ---------------------------------------------------------------------------

-- Root node (parent_id IS NULL identifies the unique root)
INSERT INTO nodes (name, description, is_active, sort_order)
VALUES ('Root', 'Root node — top of the node tree', TRUE, 0);

-- Company settings singleton (update name and timezone via settings UI after first login)
INSERT INTO company_settings (name, timezone, retention_years, node_retention_extra_years, purge_schedule)
VALUES ('My Company', 'UTC', 7, 1, 'annual');

-- Purge job state singletons
INSERT INTO purge_jobs (job_type, status) VALUES ('activity', 'idle');
INSERT INTO purge_jobs (job_type, status) VALUES ('node',     'idle');
