-- trawhile — PostgreSQL schema
-- All tables use UUID primary keys generated by gen_random_uuid().
-- One instance = one company. No multi-tenancy.
-- Table order respects FK dependencies.

-- ---------------------------------------------------------------------------
-- Company settings (singleton, one row seeded by Flyway)
-- ---------------------------------------------------------------------------

CREATE TABLE company_settings (
  id                         UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  name                       TEXT    NOT NULL,
  timezone                   TEXT    NOT NULL DEFAULT 'UTC',        -- IANA timezone
  freeze_date                DATE,                                   -- entries before this date are immutable
  retention_years            INTEGER NOT NULL DEFAULT 7,            -- minimum 2
  node_retention_extra_years INTEGER NOT NULL DEFAULT 1,            -- minimum 0; nodes deleted retention_years + node_retention_extra_years after deactivation
  purge_schedule             TEXT    NOT NULL DEFAULT 'annual',
  privacy_notice_url         TEXT                               -- optional; shown on first login alongside built-in data summary
  -- purge_schedule: 'annual' | 'semi_annual' | 'quarterly'
  -- annual:      activity Dec 31       / node Jan 31
  -- semi_annual: activity Jun 30+Dec31 / node Jul 31+Jan 31
  -- quarterly:   activity Mar31+Jun30+Sep30+Dec31 / node Apr30+Jul31+Oct31+Jan31
);

-- ---------------------------------------------------------------------------
-- Node tree
-- Root node: parent_id IS NULL (singleton, seeded by Flyway).
-- All entities (projects, work packages, tasks, absence types, etc.) are nodes.
-- Leaf node (no active children) = trackable.
-- ---------------------------------------------------------------------------

CREATE TABLE nodes (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id      UUID        REFERENCES nodes(id),
  name           TEXT        NOT NULL,
  description    TEXT,
  is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
  sort_order     INTEGER     NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deactivated_at TIMESTAMPTZ,                        -- set on deactivation, cleared on reactivation
  color          TEXT,                               -- CSS hex color e.g. '#4A90D9'; optional
  icon           TEXT,                               -- PrimeIcons identifier e.g. 'pi-briefcase'; optional
  logo           BYTEA,                              -- uploaded image, max 256 KB; takes precedence over icon
  logo_mime_type TEXT                                -- MIME type of logo e.g. 'image/png'
);

-- ---------------------------------------------------------------------------
-- Users
-- users: anchor record, never deleted, FK target for all historical data.
-- user_profile: personal data, deleted on anonymization (cascades to user_oauth_providers, quick_access).
-- No picture_url stored — profile pictures dropped (privacy; no chat/mention feature to justify them).
-- ---------------------------------------------------------------------------

CREATE TABLE users (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
  is_system_admin BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE user_profile (
  id                    UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID    NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  name                  TEXT    NOT NULL,
  gdpr_notice_accepted  BOOLEAN NOT NULL DEFAULT FALSE,  -- set true on first-login acknowledgement
  language              TEXT    NOT NULL DEFAULT 'en',   -- IETF language tag; supported: en, de, fr, es
  last_report_settings  JSONB                            -- last used report filter state; persisted for multi-device consistency
);

CREATE TABLE user_oauth_providers (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES user_profile(id) ON DELETE CASCADE,
  provider   TEXT NOT NULL,  -- 'github' | 'google' | 'apple'
  subject    TEXT NOT NULL,  -- provider's subject ID (never email)
  UNIQUE (provider, subject)
);

-- Email-only invitations. Matched on first OAuth2 login then deleted. Email never stored in users.
-- Automatically purged after 90 days if not accepted (GDPR storage limitation).
CREATE TABLE pending_memberships (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  email      TEXT        NOT NULL UNIQUE,
  invited_by UUID        NOT NULL REFERENCES users(id),
  invited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '90 days'
);

-- ---------------------------------------------------------------------------
-- Authorization
-- ---------------------------------------------------------------------------

CREATE TYPE auth_level AS ENUM ('view', 'track', 'admin');
-- Ordering: view < track < admin (PostgreSQL ENUM preserves definition order)
-- track implies view; admin implies track.
-- A grant on node N is effective on N and all its descendants (recursive CTE).

CREATE TABLE node_authorizations (
  id            UUID       PRIMARY KEY DEFAULT gen_random_uuid(),
  node_id       UUID       NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  user_id       UUID       NOT NULL REFERENCES users(id),
  authorization auth_level NOT NULL,
  UNIQUE (node_id, user_id)
);

-- ---------------------------------------------------------------------------
-- Time entries
-- Active entry: ended_at IS NULL. Partial unique index enforces at most one per user.
-- timezone: IANA string captured from browser at tracking start; stored on the entry.
-- ---------------------------------------------------------------------------

CREATE TABLE time_entries (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES users(id),
  node_id     UUID        NOT NULL REFERENCES nodes(id),
  started_at  TIMESTAMPTZ NOT NULL,
  ended_at    TIMESTAMPTZ,
  timezone    TEXT        NOT NULL,             -- IANA string from browser; private (discloses coarse location) — protected by per-owner access control on time_entries
  description TEXT,                             -- optional short note by the member
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX time_entries_one_active_per_user
  ON time_entries (user_id)
  WHERE ended_at IS NULL;

-- ---------------------------------------------------------------------------
-- Personal preferences (cascade-deleted with user_profile on anonymization)
-- ---------------------------------------------------------------------------

CREATE TABLE quick_access (
  id         UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID    NOT NULL REFERENCES user_profile(id) ON DELETE CASCADE,
  node_id    UUID    NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  UNIQUE (profile_id, node_id)
);

-- ---------------------------------------------------------------------------
-- Requests (in-app request board)
-- ---------------------------------------------------------------------------

CREATE TABLE requests (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id UUID        NOT NULL REFERENCES users(id),
  node_id      UUID        NOT NULL REFERENCES nodes(id),
  template     TEXT        NOT NULL,  -- system template ID or 'free_text'
  body         TEXT,
  status       TEXT        NOT NULL DEFAULT 'open',  -- 'open' | 'closed'
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at  TIMESTAMPTZ,
  resolved_by  UUID        REFERENCES users(id)
);

-- ---------------------------------------------------------------------------
-- Security event log (90-day retention, System Admin access only)
-- ---------------------------------------------------------------------------

CREATE TABLE security_events (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        REFERENCES users(id),  -- NULL for pre-auth events
  event_type  TEXT        NOT NULL,
  details     JSONB,
  ip_address  TEXT,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Purge job state
-- Two singleton rows seeded by Flyway: job_type = 'activity', job_type = 'node'.
-- status: 'idle' | 'active'
-- cutoff_date: set at job start, stable across restarts (idempotency anchor).
-- deleted_counts: running tally updated after each batch commit.
-- On startup: any 'active' row is resumed using stored cutoff_date.
-- ---------------------------------------------------------------------------

CREATE TABLE purge_jobs (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_type        TEXT        NOT NULL UNIQUE,  -- 'activity' | 'node'
  status          TEXT        NOT NULL DEFAULT 'idle',
  cutoff_date     DATE,
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  deleted_counts  JSONB,
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- MCP access tokens (Epic 9)
-- Raw token never stored. Only SHA-256 hash retained.
-- Revocation: soft-delete via revoked_at. Hard-delete not needed (hash is useless after revoke).
-- ---------------------------------------------------------------------------

CREATE TABLE mcp_tokens (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES users(id),
  token_hash   TEXT        NOT NULL UNIQUE,  -- SHA-256 hex of the raw token
  label        TEXT        NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  expires_at   TIMESTAMPTZ,                  -- NULL = non-expiring
  revoked_at   TIMESTAMPTZ                   -- NULL = active
);

CREATE INDEX mcp_tokens_user_id_idx ON mcp_tokens (user_id);

-- ---------------------------------------------------------------------------
-- Core authorization queries (reference)
-- ---------------------------------------------------------------------------

-- Q1: nodes visible to a user (grant on N = effective on N and all descendants)
-- WITH RECURSIVE visible AS (
--   SELECT n.id FROM nodes n
--   JOIN node_authorizations na ON na.node_id = n.id
--   WHERE na.user_id = :user_id
--   UNION ALL
--   SELECT n.id FROM nodes n
--   JOIN visible v ON n.parent_id = v.id
-- )
-- SELECT id FROM visible;

-- Q2: effective authorization of a user on a specific node (walk upward)
-- WITH RECURSIVE ancestors AS (
--   SELECT id, parent_id FROM nodes WHERE id = :node_id
--   UNION ALL
--   SELECT n.id, n.parent_id FROM nodes n JOIN ancestors a ON n.id = a.parent_id
-- )
-- SELECT MAX(na.authorization) AS effective_authorization
-- FROM ancestors a JOIN node_authorizations na ON na.node_id = a.id
-- WHERE na.user_id = :user_id;

-- Q3: guard — does user have at least level X on node N?
-- WITH RECURSIVE ancestors AS (
--   SELECT id, parent_id FROM nodes WHERE id = :node_id
--   UNION ALL
--   SELECT n.id, n.parent_id FROM nodes n JOIN ancestors a ON n.id = a.parent_id
-- )
-- SELECT EXISTS (
--   SELECT 1 FROM ancestors a JOIN node_authorizations na ON na.node_id = a.id
--   WHERE na.user_id = :user_id AND na.authorization >= :required_level
-- );

-- Q4: all users with at least level X on node N
-- WITH RECURSIVE ancestors AS (
--   SELECT id, parent_id FROM nodes WHERE id = :node_id
--   UNION ALL
--   SELECT n.id, n.parent_id FROM nodes n JOIN ancestors a ON n.id = a.parent_id
-- )
-- SELECT na.user_id, MAX(na.authorization) AS effective_authorization
-- FROM ancestors a JOIN node_authorizations na ON na.node_id = a.id
-- GROUP BY na.user_id
-- HAVING MAX(na.authorization) >= :required_level;
